SELECT COUNT(DISTINCT DEPT) FROM STUDENT WHERE DEPT = "컴퓨터과"

SELECT 학번, 이름 FROM 학생 WHERE 학년 IN (3, 4);

CREATE INDEX IDX_NAME ON STUDENT(NAME);

DELETE FROM 학생 WHERE 이름 = "민수";

ALTER TABLE 학생 ADD 주소 VARCHAR(20);

SELECT 학생정보.학번, 학생정보.이름, 학과정보.학과, 학과정보.지도교수
FROM 학생정보 JOIN 학과정보 ON 학생정보.학과 = 학과정보.학과;

UPDATE 회원 SET 전화번호 = "010-14"
WHERE 회원번호 = "N4";

-- 16번 [21년 2회]
SELECT *
FROM 학생
WHERE 이름 LIKE "이%" ORDER BY 이름 DESC;

SELECT NAME, SCORE
FROM 성적
ORDER BY SCORE DESC;

SELECT COUNT(*) CNT FROM SOO CROSS JOIN JEBI
WHERE SOO.NAME LIKE JEBI.RULE;

SELECT COUNT(COL2)
FROM TB
WHERE COL1 IN(2,3) OR COL2 IN(3,5);

SELECT DISTINCT COUNT(부서코드) FROM 직원;

DELETE FROM 부서 WHERE 부서코드 = '20';
SELECT COUNT(DISTINCT 직원코드) FROM 직원;

SELECT 과목이름, MIN(점수) AS 최소점수, MAX(점수) AS 최대점수 FROM 성적
GROUP BY 과목이름
HAVING AVG(점수) >= 90;

SELECT 학과, COUNT(학과) AS '학과별튜플수' FROM 학생
GROUP BY 학과;

SELECT 학과, COUNT(*) AS '학과별튜플수' FROM 학생
GROUP BY 학과;